language: ruby
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
rvm:
  - 2.2.5
install:
  - gem install jekyll
  - gem install html-proofer
script:
  - jekyll build
  - htmlproofer _site --only-4xx